### ISSUE TITLE
Error in description of parallax calculation

### ISSUE THREAD

**Issue by zebulon2** [aendie/SFalmanac-Py3#1]
This is fantastic work! I however spotted what I believe to be a mistake in the Parallax description in increments.py file. It says "The parallax ($P$) can be calculated from horizontal parallax ($HP$) and observed altitude $H_o$ with the following formula:
\[P=\cos({HP})\]".

It should however say: "The parallax ($P$) can be calculated from horizontal parallax ($HP$) and apparent altitude $H_a$ with the following formula: P = HP x cos(Ha)
which is the general formula for this correction, and the one you use in the parallax(hp, deg, min) function in increments.py.

Besides and to be thorough, I found other variations of the same calculation such as in https://www.siranah.de/html/sail040p.htm. Therefore the correct formula is given as:
P = asin( sin(HP) * cos(Ha) ) which gives the almost same result as the formula above. In this formula sin(HP) is equal to the radius of the earth divided by the distance to the celestial body.

To finish, some sources suggest also to use parallax for the sun (when Earth is at aphelion this means a 0 to 0.14' correction) for greater precision. I even read on another site (https://www.navsoft.com/html/corrections.html) that one can introduce a correction for the radius of the earth based on latitude, but I think this is overkill considering this is probably not significant.

**Comment by aendie** [comment]
Dear Erik,

 

Many thanks for your contribution! 

 

I will incorporate your suggestions. I have cross-checked with Johannes, who publishes the almanacs (in slightly modified form) on https://thenauticalalmanac.com/. His feedback was …

For this reason Dr. Rodegerdts's formulas page isn't included in The Nautical Almanacs as I perceived this specific formula would cause problems.  When shooting Mars or Venus any correction for parallax, as Enno says on that page of increments, isn't necessary unless attempting to get greater accuracy.  For the Moon's parallax I personally use the following same first formula the gentlemen suggested. 

Moon's Parallax
Get Moon's HP value from Nautical Almanac daily pages
Formula- HP x Cos(Ha)
Moon's Semi-Diameter
Example- 0° 59.3' x cos(31° 1.9' )= 0° 50.8'


The USNO published Nautical Almanac has in the "Yellow pages" the Moon's Altitude Correction Tables at the back of the book.  Using these tables there's no need to solve for parallax.  Here they are on the site; 

Moon Altitude Correction Tables <https://thenauticalalmanac.com/Altitude%20Correction%20Tables%20for%20the%20Moon.pdf> 

 

I originally forked Pyalmanac (Python 2) from Dr. Enno Rodegerdts and found several mistakes and an omission (that duplicate moonrise/moonsets on one given day were not displayed at all). I have summarized these original findings here: https://github.com/aendie/Pyalmanac-Py2

 

Enno Rodegerdts gave me permission to update and maintain his GitHub site: https://github.com/rodegerdts/Pyalmanac His website is here: https://sv-inua.net/the-nautical-almanac

 

I have hardly looked at increments.py … I remember I fixed the problem that it occasionally displayed 60 seconds of arc instead of rounding up to the next minute. So I have only two versions of increments.py (Python 2 and Python 3) that I plug into all my repositories. I will now update all seven repos.

 

I have been in contact with Brandon Rhodes – the mastermind behind PyEphem and Skyfield – and he’s been really helpful when I had issues, e.g.

https://github.com/skyfielders/python-skyfield/issues/339

https://github.com/skyfielders/python-skyfield/issues/288

https://github.com/skyfielders/python-skyfield/issues/280

 

… so you see it was a bit of a struggle for me to get to where I am today.

 

Kind Regards from Munich, Bavaria, Germany!

Andrew

**Comment by aendie** [comment]
Dear Erik,

Many thanks for your contribution! 

I will incorporate your suggestions. I have cross-checked with Johannes, who publishes the almanacs (in slightly modified form) on https://thenauticalalmanac.com/. His feedback was …

-----------------------------------------------------------------
For this reason Dr. Rodegerdts's formulas page isn't included in The Nautical Almanacs as I perceived this specific formula 
would cause problems.  When shooting Mars or Venus any correction for parallax, as Enno says on that page of increments, 
isn't necessary unless attempting to get greater accuracy.  For the Moon's parallax I personally use the following same first 
formula the gentlemen suggested. 

**Moon's Parallax**
Get Moon's HP value from Nautical Almanac daily pages
Formula- HP x Cos(Ha)
Moon's Semi-Diameter
Example- 0° 59.3' x cos(31° 1.9' )= 0° 50.8'

The USNO published Nautical Almanac has in the "Yellow pages" the Moon's Altitude Correction Tables at the back of the 
book.  Using these tables there's no need to solve for parallax.  Here they are on the site; 

Moon Altitude Correction Tables 
<https://thenauticalalmanac.com/Altitude%20Correction%20Tables%20for%20the%20Moon.pdf> 

-----------------------------------------------------------------

I originally forked Pyalmanac (Python 2) from Dr. Enno Rodegerdts and found several mistakes and an omission (that duplicate moonrise/moonsets on one given day were not displayed at all). I have summarized these original findings here: https://github.com/aendie/Pyalmanac-Py2

Enno Rodegerdts gave me permission to update and maintain his GitHub site: https://github.com/rodegerdts/Pyalmanac His website is here: https://sv-inua.net/the-nautical-almanac

I have hardly looked at increments.py … I remember I fixed the problem that it occasionally displayed 60 seconds of arc instead of rounding up to the next minute. So I have only two versions of increments.py (Python 2 and Python 3) that I plug into all my repositories. I will now update all seven repos.

I have been in contact with Brandon Rhodes – the mastermind behind PyEphem and Skyfield – and he’s been really helpful when I had issues, e.g.

<https://github.com/skyfielders/python-skyfield/issues/339>
<https://github.com/skyfielders/python-skyfield/issues/288>
<https://github.com/skyfielders/python-skyfield/issues/280>

 … so you see it was a bit of a struggle for me to get to where I am today.

Kind Regards from Munich, Bavaria, Germany!

Andrew

**Comment by aendie** [comment]
Your suggestion has been merged; all seven repositories (containing _increments.py_) have_ been updated; issue closed.
